---
# tasks file for enable_zswap
- name: Enable zswap tweak for improved performance on Pi4
  become: true
  become_user: root
  shell: sed -i -e 's/$/ zswap.enabled=1/' /boot/firmware/cmdline.txt
  when: (ansible_architecture == "aarch64") and (ansible_distribution == "Ubuntu")

- name: Reboot Rpi4
  reboot:
    msg: "Reboot initiated by Ansible."
    # connection_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
  become: true
  when: (ansible_architecture == "aarch64") and (ansible_distribution == "Ubuntu")

- name: Wait for reboot to complete
  wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 300
  become: true
  when: (ansible_architecture == "aarch64") and (ansible_distribution == "Ubuntu")

- name: Check uptime
  shell: "uptime"
  register: uptime
  become: true
  when: (ansible_architecture == "aarch64") and (ansible_distribution == "Ubuntu")

- debug: var=uptime
