---
- name: Set default git branch to "{{ git_default_branch_name }}"
  git_config:
    name: init.defaultBranch
    scope: global
    value: "{{ git_default_branch_name }}"

- name: Set git user
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: Set git email to "{{ git_user_email }}"
  git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
