###########
# Ansible #
###########
ansible_python_interpreter: "/usr/bin/python3"
pyenv_python_ver: "3.11.4"

## User for connection. I use a service account, "ansible_svc"
ansible_ssh_user: "ubuntu"
## Path to SSH key (note: you must copy this to the host with ssh-copy-id before using Ansible)
ansible_ssh_private_key_file: "/home/<user>/.ssh/<private_key>"

## For path substitution, i.e. "/home/{{ remote_host_user }}"
remote_host_user: "ubuntu"

tailscale_preauth_key: ""

#######
# Git #
#######
git_default_branch_name: "main"
git_user_name: "gitUsername"
git_user_email: "no@no.com"

###########
# Cluster #
###########

cl_srv1_ip: "192.168.1.xxx"
cl_ag1_ip: "192.168.1.xxx"
cl_ag2_ip: "192.168.1.xxx"

## DNS
dns_ns: "192.168.1.xxx"

###################
# CNI Plugin Vars #
###################

cni_app: cni
## Find current version at:
#  https://github.com/containernetworking/plugins/releases
cni_version: 1.3.0
cni_os: linux
## amd64, arm, arm64
cni_arch: arm64
cni_dl_url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/cni-plugins-{{ cni_os }}-{{ cni_arch }}-v{{ cni_version }}.tgz"
cni_plugins_dir: /opt/cni/bin
cni_plugins_dir_mode: "0755"
