---
- name: Uninstall Consul
  hosts: all

  tasks:
    - name: "Uninstall Consul"
      include_role:
        name: ../../roles/common/uninstall/uninstall-hashi-apps
        tasks_from: uninstall-consul.yml

    - name: "Post-Uninstall Consul Cleanup"
      include_role:
        name: ../../roles/common/uninstall/uninstall-hashi-apps
        tasks_from: uninstall-consul_cleanup.yml

    - name: "Reboot server. Reason: Consul uninstall"
      include_role:
        - ../../roles/maint/reboot-system
