---
# tasks file for install-hashi-up
## Get all installed packages
- name: "[All OS Types] [Hashi-Up] Check packes"
  ansible.builtin.package_facts:
    manager: auto

- include_tasks: install-dependencies.yml
- include_tasks: install-hashi-up.yml
