---
- name: "[DEBIAN] Check if reboot is required"
  register: deb_reboot_required
  stat:
    path: /run/reboot-required
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: "[Debian] Reboot server for updates"
  reboot:
    msg: "Reboot initiated by Ansible. Reason: kernel updates"
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
  become: true
  when: (deb_reboot_required.stat.exists) and (ansible_facts['os_family'] == "Debian")
