---
- name: "Reboot server for updates"
  reboot:
    msg: "Reboot initiated by Ansible. Reason: kernel updates"
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
  become: true
