---
- name: "[Debian Family] [Pipx] Install dependencies"
  apt:
    name: ["python3", "python3-pip", "python3-argcomplete", "python3-venv"]
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: "[RedHat Family] [Pipx] Install dependencies"
  yum:
    name: ["python3", "python3-pip", "python3-argcomplete", "python3-venv"]
    state: present
  become: true
  when: ansible_facts['os_family'] == "RedHat"

# - name: "[All OS Types] [Pipx] Install pipx"
#   pip:
#     name: pipx
#     extra_args: --user

- name: "[All OS Types] [Pipx] Install pipx"
  shell: |
    python3 -m pip install --user pipx
  become: true
  become_user: "{{ remote_host_user }}"

- name: "[All OS Types] [Pipx] run ensurepath"
  shell: |
    python3 -m pipx ensurepath
  become: true
  become_user: "{{ remote_host_user }}"
