---
- name: "[All OS Types] [Pyenv Setup] Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "[All OS Types] [Pyenv Setup] Check if dir exists: /home/{{ remote_host_user }}/.pyenv"
  stat:
    path: "/home/{{ remote_host_user }}/.pyenv"
  become: true
  register: pyenv_dir

- name: "[All OS Types] [Pyenv Setup] Check if dir exists: /home/{{ remote_host_user }}/.pyenv/{{ pyenv_python_ver }}"
  stat:
    path: "/home/{{ remote_host_user }}/.pyenv/versions/{{ pyenv_python_ver }}"
  become: true
  register: pyenv_ver_exists

- include_tasks: install-dependencies.yml
  when: (ansible_facts['os_family'] == "Debian") and ("pyenv" not in ansible_facts.packages)

- include_tasks: install-pyenv.yml
  when: ("pyenv" not in ansible_facts.packages) and (not pyenv_dir.stat.exists)

- include_tasks: configure-env.yml

- include_tasks: pyenv-global-python.yml
  # when: not pyenv_ver_exists.stat.exists
