---
- name: "[All OS Types] [SSH] Create /home/{{ remote_host_user }}/.ssh/config if it does not exist"
  file:
    path: "/home/{{ remote_host_user }}/.ssh/config"
    state: touch
    mode: "0644"
  become: true

- name: "[All OS Types] [SSH] Add cluster nodes to /home/{{ remote_host_user }}/.ssh/config"
  blockinfile:
    path: "/home/{{ remote_host_user }}/.ssh/config"
    block: "{{ lookup('template', 'ssh_config.j2') }}"

- name: "[All OS Types] [SSH] Set chmod on /home/{{ remote_host_user }}/.ssh/config"
  file:
    path: "/home/{{ remote_host_user }}/.ssh/config"
    mode: "0644"
  become: true
