---
# tasks file for roles/common/install-tmux

## Get all installed packages
- name: "[All OS Types] [Tmux] Check packes"
  ansible.builtin.package_facts:
    manager: auto

- name: "[Debian Family] [Tmux] Install Tmux"
  include_tasks: install-tmux_debian-family.yml
  when: (ansible_facts['os_family'] == "Debian") and ("tmux" not in ansible_facts.packages)

- name: "[All OS Types] [Tmux] Configure Tmux"
  include_tasks: configure-tmux.yml

- name: "[All OS Types] [Tmux] Install Tmux plugins"
  include_tasks: install-tmux-plugins.yml
