---
- name: "[All OS Types] [Docker Setup] Check if 'docker' group exists"
  ansible.builtin.group:
    name: "docker"
    state: present
  become: true

- name: "[All OS Types] [Docker Setup] Add remote user: {{ remote_host_user }} to group 'docker'"
  ansible.builtin.user:
    name: "{{ remote_host_user }}"
    groups: "docker"
    append: yes
  become: true

- name: "[Debian] [Docker Setup] Enable & Start Docker service"
  become: true
  service:
    name: docker
    enabled: true
    state: started
  when: (ansible_facts['os_family'] == "Debian")
