- name: Remove lxd snap
  # shell: snap remove lxd
  snap:
    name: "lxd"
    state: absent
  become: true
  when: ansible_distribution == "Ubuntu"
  ignore_errors: true

- name: Remove core20 snap
  # shell: snap remove core18
  snap:
    name: "core20"
    state: absent
  become: true
  when: ansible_distribution == "Ubuntu"
  ignore_errors: true

- name: Remove snapd snap
  # shell: snap remove snapd
  snap:
    name: "snapd"
    state: absent
  become: true
  when: ansible_distribution == "Ubuntu"
  ignore_errors: true

- name: Purge snapd
  apt:
    name: snapd
    purge: yes
    state: absent
  become: true
  when: ansible_distribution == "Ubuntu"
  ignore_errors: true

- name: Check if /root/snap dir exists
  stat:
    path: "/root/snap"
  become: true
  register: root_snap_dir

- name: Check if /snap dir exists
  stat:
    path: "/snap"
  become: true
  register: snap_dir

- name: Check if /var/snap dir exists
  stat:
    path: "/var/snap"
  become: true
  register: var_snap_dir

- name: Check if /var/lib/snapd dir exists
  stat:
    path: "/var/lib/snapd"
  become: true
  register: var_lib_snap_dir

- name: Remove /root/snap directory
  file:
    state: absent
    path: "/root/snap"
  become: true
  when: root_snap_dir.stat.exists

- name: Remove /snap directory
  file:
    state: absent
    path: "/snap"
  become: true
  when: snap_dir.stat.exists

- name: Remove /var/snap directory
  file:
    state: absent
    path: "/var/snap"
  become: true
  when: var_snap_dir.stat.exists

- name: Remove /var/lib/snap directory
  file:
    state: absent
    path: "/var/lib/snap"
  become: true
  when: var_lib_snap_dir.stat.exists
