---
## Ensure pyenv config block exists in .bashrc
- name: "[Debian] [Pyenv Setup] Check if Pyenv config exists in /home/{{ remote_host_user }}/.bashrc"
  blockinfile:
    path: "/home/{{ remote_host_user }}/.bashrc"
    block: |
      ## Pyenv
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
  when: ansible_facts['os_family'] == "Debian"
