---
- name: "[All OS Types] [Pyenv Setup] Update Pyenv versions"
  shell: "/home/{{ remote_host_user }}/.pyenv/bin/pyenv update"

- name: "[All OS Types] [Pyenv Setup] Install environment, Python version: {{ pyenv_python_ver }}"
  shell: "/home/{{ remote_host_user }}/.pyenv/bin/pyenv install {{ pyenv_python_ver }}"

- name: "[All OS Types] [Pyenv Setup] Set global Python to pyenv version {{ pyenv_python_ver }}"
  shell: "/home/{{ remote_host_user }}/.pyenv/bin/pyenv global {{ pyenv_python_ver }}"

- name: "[All OS Types] [Pyenv Setup] Set local Python to pyenv version {{ pyenv_python_ver }}"
  shell: "/home/{{ remote_host_user }}/.pyenv/bin/pyenv local {{ pyenv_python_ver }}"

- name: "[All OS Types] [Pyenv Setup] Set shell Python to pyenv version {{ pyenv_python_ver }}"
  shell: "/home/{{ remote_host_user }}/.pyenv/bin/pyenv shell {{ pyenv_python_ver }}"
