- name: "[All OS Types] [Pipx] Load pyenv"
  shell: |-
    export PYENV_ROOT="/home/{{ remote_host_user }}/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    pyenv global "{{ pyenv_python_ver }}"
